blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('post/new/', views.post_new, name='post_new'),
    path('post/<int:pk>/edit/', views.post_edit, name='post_edit'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('admin/', admin.site.urls),
    path('survey/', include('survey.urls')),

]

survey/urls.py
from django.urls import path
from. import views

app_name='survey'

urlpatterns=[
    path('', views.index, name='index'),
    path('<int:question_id>/',views.detail,name='detail'),
    path('<int:question_id>/vote',views.vote,name='vote'),
    path('<int:question_id>/results', views.results, name='results'),
    ]

blog/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone


class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(
            default=timezone.now)
    published_date = models.DateTimeField(
            blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

survey/models.py
import datetime
from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text=models.CharField(max_length=200)
    pup_date=models.DateTimeField('date published')

    def was_published_recently(self):
        return self.pup_date>= timezone.now()-datetime.timedelta(days=1)

    def __str__(self):
        return self.question_text

class Choice(models.Model):
    question=models.ForeignKey(Question,on_delete=models.CASCADE)
    choice_text=models.CharField(max_length=200)
    votes=models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

blog/forms.py
from django import forms

from .models import Post

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'text',)

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.utils import timezone
from .models import Post
from .forms import PostForm
from django.shortcuts import redirect


def post_list(request):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
    return render(request, 'blog/post_list.html', {'posts': posts})

def post_detail(request, pk):
    Post.objects.get(pk=pk)
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'blog/post_detail.html', {'post': post})

def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('post_detail', pk=post.pk)
    else:
        form = PostForm()
    return render(request, 'blog/post_edit.html', {'form': form})

def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(instance=post,)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('post_detail', pk=post.pk)
    else:
        form = PostForm(instance=post)
    return render(request, 'blog/post_edit.html', {'form': form})

survey/views.py
from django.shortcuts import render, get_object_or_404
from survey.models import Question, Choice
from django.http import HttpResponseRedirect
from django.urls import reverse

def index(request):
    latest_question_list=Question.objects.all().order_by('-pup_date')[:5]
    context={'latest_question_list':latest_question_list}
    print(latest_question_list)
    return render(request, 'survey/index.html', context)

def detail(request, question_id):
    question= get_object_or_404(Question, pk=question_id)
    return render(request, "survey/detail.html", {'question': question})

def vote(request, question_id):
    question=get_object_or_404(Question, pk=question_id)
    try:
        selected_choice=question.choice_set.get(pk=request.POST['choice'])
    except(KeyError,Choice.DoesNotExist):
        return render(request, 'survey/detail.html',{'question':question,'error_message':"You didn't select a choice"})

    else:
        selected_choice.votes +=1
        selected_choice.save()
        return HttpResponseRedirect(reverse('survey:results',args=(question_id,)))

def results(request,question_id):
        question=get_object_or_404(Question, pk=question_id)
        test = [1,2,3,4,5]
        return render(request, 'survey/results.html',{'question':question, 'test': test})

blog/templates/blog/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head lang="en">
        <title>Django Girls blog</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="{% static 'css/blog.css' %}">
    </head>
    <body>
        <div class="page-header">

            <a href="{% url 'post_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
            <h1><a href="/">희진이의 과목 정리 블로그</a></h1>
        </div>
        <nav>
        <div>
            <li><a href="/">과목</a></li>
            <li><a href="survey/">어려운 과목 조사</a></li>

        </div>
    </nav>

        <div class="content container">
            <div class="row">
                <div class="col-md-8">
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
        </div>
    </body>
</html>

blog/templates/blog/post_detail.html
<!DOCTYPE html>
{% extends 'blog/base.html' %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>huijin blog</title>
</head>
<body>
{% block content %}
    <div class="post">
        {% if post.published_date %}
            <div class="date">
                {{ post.published_date }}
            </div>
        {% endif %}
        <a class="btn btn-default" href="{% url 'post_edit' pk=post.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
        <h1>{{ post.title }}</h1>
        <p>{{ post.text|linebreaksbr }}</p>
    </div>
{% endblock %}
</body>
</html>

blog/templates/blog/post_edit.html
<!DOCTYPE html>
{% extends 'blog/base.html' %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>huijin blog</title>
</head>
 <div class="page-header">

            <a href="{% url 'post_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
            <h1><a href="/">희진이의 과목 정리 블로그</a></h1>
        </div>
        <nav>
        <div>
            <li><a href="/">과목</a></li>
            <li><a href="survey/">어려운 과목 조사</a></li>

<body>
{% block content %}
    <h1>New post</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}
</body>
</html>

blog/templates/blog/post_list.html
<!DOCTYPE html>
{% extends 'blog/base.html' %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>huijin blog</title>
        <title>Django Girls blog</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link rel="stylesheet" href="{% static 'css/blog.css' %}">
</head>
 <body>
    <header>
        <div class="page-header">
            <h1><a href="">희진이의 과목 정리 블로그</a></h1>
        </div>
    </header>

    <nav>
        <div>
            <li><a href="/">과목</a></li>
            <li><a href="survey/">어려운 과목 조사</a></li>

        </div>
    </nav>

    {% block content %}
            {% for post in posts %}
                <div class="post">
                    <div class="date">
                        <p>published: {{ post.published_date }}</p>
                    </div>
                    <h1><a href="{% url 'post_detail' pk=post.pk %}">{{ post.title }}</a></h1>
                    <p>{{ post.text|linebreaksbr }}</p>
                </div>
            {% endfor %}
    {% endblock %}

    </body>
</html>

survey/templates/survey/detail.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>huijin blog</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="{% static 'css/survey.css' %}">
</head>
<body>
 <div class="page-header">
            <h1><a href="/">희진이의 과목 정리 블로그</a></h1>
        </div>
        <nav>
        <div>
            <li><a href="/">과목</a></li>
            <li><a href="survey/">어려운 과목 조사</a></li>

        </div>
        </nav>
<div class="question2">
<h1>{{question.question_text}}</h1>

{% if error_message %}<p><strong>{{error_message}}</strong></p>{%endif%}

<form action="{% url 'survey:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{forloop.counter}}" value="{{choice.id}}"/>
    <label for="choice{{forloop.counter}}">{{choice.choice_text}}</label><br/>
{%endfor %}
    <input type="submit" value="투표하기" />
</div>
</form>
</body>
</html>

survey/templates/survey/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>huijin blog</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="{% static 'css/survey.css' %}">
</head>
<body>
     <div class="page-header">
            <h1><a href="/">희진이의 과목 정리 블로그</a></h1>
        </div>
        <nav>
        <div>
            <li><a href="/">과목</a></li>
            <li><a href="survey/">어려운 과목 조사</a></li>

        </div>
        </nav>
{% if latest_question_list %}
    <div class="question">
     <ul>
        {% for question in latest_question_list %}
            <li><a href="/survey/{{question.id}}">{{question.question_text}}</a></li>
        {% endfor %}

    </ul>
    </div>
{% else %}
    <p>No survey are available.</p>

{% endif %}
</body>
</html>

survey/templates/survey/results.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>huijin blog</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="{% static 'css/survey.css' %}">
</head>
<body>
<div class="page-header">
            <h1><a href="/">희진이의 과목 정리 블로그</a></h1>
        </div>
        <nav>
        <div>
            <li><a href="/">과목</a></li>
            <li><a href="survey/">어려운 과목 조사</a></li>

        </div>
        </nav>
<div class="question3">
<h1>{{question.question_text}}</h1>

<ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }}-{{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
</ul>

<a href="{% url 'survey:detail' question.id%}">다시 투표하기</a>
</div>
</body>
</html>